/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    kotlin("jvm") version "1.9.22"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0-RC")
    
    implementation("io.github.oshai:kotlin-logging-jvm:5.1.0")
    // implementation("org.slf4j:slf4j-simple:2.0.3")
    implementation("ch.qos.logback:logback-classic:1.4.14")
    
    api("com.malinskiy.adam:adam:0.5.2")
}

application {
    // Define the main class for the application.
    mainClass.set("com.awalsh128.thetowerbot.AppKt")
}
